name: simple web example CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.13.1"

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build Test
        run: npm run build

      - name: Image Tag Test
        run: chmod 775 ./extract-image-tag_linux_amd64 && ./extract-image-tag_linux_amd64 -f simple-web.yml -tu https://registry.hub.docker.com/v1/repositories/a3magic3pocket/simple-web/tags
