name: Build docker image
on:
  workflow_run:
    workflows: ["simple web example CI"]
    branches: [main]
    types: 
      - completed
jobs:
  push_to_registry:
    environment: dockerhub
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - run: chmod 775 ./extract-image-tag_linux_amd64 
      - run: echo "TAG=`./extract-image-tag_linux_amd64 -f simple-web.yml -tu https://registry.hub.docker.com/v1/repositories/a3magic3pocket/simple-web/tags`" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: a3magic3pocket/simple-web:${{ env.TAG }}
